name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
      fail-fast: false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter (if configured)
        run: npm run lint --if-present
      
      - name: Run tests
        run: npm test
      
      - name: Run test coverage
        run: npm run test:coverage
        if: matrix.node-version == 18  # Only run coverage on one Node version
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: matrix.node-version == 18
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  security-audit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run security audit
        run: npm audit
      
      - name: Check for vulnerabilities
        run: npm audit --audit-level high

  node16-compatibility:
    runs-on: ubuntu-latest
    continue-on-error: true  # Allow this job to fail without failing the workflow
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Install dependencies (compatibility mode)
        run: |
          echo "Testing Node.js 16 compatibility..."
          npm ci --legacy-peer-deps || npm install --legacy-peer-deps || echo "Dependency installation failed on Node.js 16"
      
      - name: Run basic tests (if dependencies installed)
        run: |
          if npm list > /dev/null 2>&1; then
            echo "Dependencies installed, running tests..."
            npm test || echo "Tests failed on Node.js 16 - compatibility issues detected"
          else
            echo "Dependencies not fully compatible with Node.js 16, skipping tests"
          fi
